
/**************************************************************
 *	
 *	punchsound, 8 bit, 11025Hz,
 *	1 channel, 4120 bytes/channel
 *	Total Size: 1 * 4120 + 4 (header) = 4360 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Travis\Music\punchsound.wav
 *	Time-stamp: Tue Dec 04 22:27:01 2018
 *	
 **************************************************************/

#ifndef __PUNCHSOUNDH__
#define __PUNCHSOUNDH__

#define PUNCHSOUNDFREQ 11025
#define PUNCHSOUNDLEN 4120

extern const unsigned char punchsound[4120];

#endif /* __PUNCHSOUNDH__ */
