
/**************************************************************
 *	
 *	fightsound, 8 bit, 11025Hz,
 *	1 channel, 398880 bytes/channel
 *	Total Size: 1 * 398880 + 4 (header) = 398924 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Travis\Music\fightsound.wav
 *	Time-stamp: Fri Nov 30 21:53:28 2018
 *	
 **************************************************************/

#ifndef __FIGHTSOUNDH__
#define __FIGHTSOUNDH__

#define FIGHTSOUNDFREQ 11025
#define FIGHTSOUNDLEN 398880

extern const unsigned char fightsound[398880];

#endif /* __FIGHTSOUNDH__ */
