
/**************************************************************
 *	
 *	startsound, 8 bit, 11025Hz,
 *	1 channel, 1786176 bytes/channel
 *	Total Size: 1 * 1786176 + 4 (header) = 1786416 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Travis\Documents\Audacity\ost\startsound.wav
 *	Time-stamp: Thu Nov 29 14:41:04 2018
 *	
 **************************************************************/

#ifndef __STARTSOUNDH__
#define __STARTSOUNDH__

#define STARTSOUNDFREQ 11025
#define STARTSOUNDLEN 1786176

extern const unsigned char startsound[1786176];

#endif /* __STARTSOUNDH__ */
