
/**************************************************************
 *	
 *	knifesound, 8 bit, 11025Hz,
 *	1 channel, 5661 bytes/channel
 *	Total Size: 1 * 5661 + 4 (header) = 5901 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Travis\Music\knifesound.wav
 *	Time-stamp: Tue Dec 04 22:30:27 2018
 *	
 **************************************************************/

#ifndef __KNIFESOUNDH__
#define __KNIFESOUNDH__

#define KNIFESOUNDFREQ 11025
#define KNIFESOUNDLEN 5661

extern const unsigned char knifesound[5661];

#endif /* __KNIFESOUNDH__ */
